name: 01-basic-first-workflow

on:
  workflow_dispatch:





jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v5
      - name: Print Hello World
        uses: ./.github/action/print-hello-world
