name: 01-basic-first-workflow

on:
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'Makrem41298' }}
    steps:
      - name: Print Hello World
        run: echo "test ok"
