name: 01-baisc-first-workflow.yml
on:
  pull_request:
    branches:
      - testPulrequest
    types:
      - closed


jobs:
  print-hello-word:
    runs-on: ubuntu-latest
    steps:
      - name: Print Helow word
        run: echo "Hello word"


